export const API_OPTIONS_SUFFIX = "/options";
export const API_ACCOUNTS_SUFFIX = "/accounts";
export const API_PERMISSIONS_SUFFIX = "/permissions";
export const API_ROLES_SUFFIX = "/roles";
export const API_POSTS_SUFFIX = "/posts";
export const API_POST_SUFFIX = "/post";
export const API_MEDIA_SUFFIX = "/media";
export const API_PROFILE_SUFFIX = "/profile";
export const API_NOTIFICATIONS_SUFFIX = "/notifications";
export const API_PARTS_SUFFIX = "/parts";
export const API_AUTH_SUFFIX = "/auth";
export const API_ADMIN_SUFFIX = "/admin";
export const API_FRONT_SUFFIX = "/front";
export const API_EXEC_STATES_SUFFIX = "/execstates";
export const API_NOTIFY_TYPES_SUFFIX = "/notifytypes";
export const API_ASSIGNS_SUFFIX = "/assigns";
export const API_EXECUTORS_SUFFIX = "/executors";
export const API_MENU_SUFFIX = "/menu";

export const API_PROFILE = API_PROFILE_SUFFIX;

// Front
export const API_FRONT_MENU = API_FRONT_SUFFIX + API_MENU_SUFFIX;
export const API_FRONT_POSTS_POST_VIEW = API_FRONT_SUFFIX + API_POSTS_SUFFIX + API_POST_SUFFIX + '/';

// Admin
export const API_ADMIN_OPTIONS = API_ADMIN_SUFFIX + API_OPTIONS_SUFFIX;
export const API_ADMIN_ACCOUNTS = API_ADMIN_SUFFIX + API_ACCOUNTS_SUFFIX;
export const API_ADMIN_PERMISSIONS = API_ADMIN_SUFFIX + API_PERMISSIONS_SUFFIX;
export const API_ADMIN_ROLES = API_ADMIN_SUFFIX + API_ROLES_SUFFIX;
export const API_ADMIN_POSTS = API_ADMIN_SUFFIX + API_POSTS_SUFFIX;
export const API_ADMIN_MEDIA = API_ADMIN_SUFFIX + API_MEDIA_SUFFIX;


export const API_ADMIN_NOTIFICATIONS = API_ADMIN_SUFFIX + API_NOTIFICATIONS_SUFFIX;

export const API_ADMIN_NOTIFICATIONS_EXEC_STATES = API_ADMIN_NOTIFICATIONS + API_PARTS_SUFFIX + API_EXEC_STATES_SUFFIX;
export const API_ADMIN_NOTIFICATIONS_TYPES = API_ADMIN_NOTIFICATIONS + API_PARTS_SUFFIX + API_NOTIFY_TYPES_SUFFIX;
export const API_ADMIN_NOTIFICATIONS_ASSIGNS = API_ADMIN_NOTIFICATIONS + API_PARTS_SUFFIX + API_ASSIGNS_SUFFIX;
export const API_ADMIN_NOTIFICATIONS_EXECUTORS = API_ADMIN_NOTIFICATIONS + API_PARTS_SUFFIX + API_EXECUTORS_SUFFIX;


