export const PATH_ROOT = '/';

export const PATH_REL_PANEL = '/panel';
export const PATH_REL_FRONT = '/front';

export const PATH_REL_LOGIN = '/login';
export const PATH_REL_LOGOUT = '/logout';
export const PATH_REL_PROFILE = '/profile';
export const PATH_REL_ACCOUNTS = '/accounts';
export const PATH_REL_PERMISSIONS = '/permissions';
export const PATH_REL_ROLES = '/roles';
export const PATH_REL_OPTIONS = '/options';
export const PATH_REL_POSTS = '/posts';
export const PATH_REL_MEDIA = '/media';
export const PATH_REL_ADMIN = '/admin';
export const PATH_REL_NOTIFICATIONS = "/notifications"
export const PATH_REL_PARTS = "/parts"
export const PATH_REL_EXEC_STATES = "/execstates"
export const PATH_REL_NOTIFICATION_TYPES = "/notifytypes"
export const PATH_REL_ASSIGNS = "/assigns"
export const PATH_REL_EXECUTORS = "/executors"

export const PATH_PANEL = PATH_REL_PANEL;

export const PATH_PANEL_ADMIN = PATH_REL_PANEL + PATH_REL_ADMIN;

export const PATH_LOGOUT = PATH_REL_LOGOUT;

// FRONT
export const PATH_FRONT = PATH_REL_FRONT;

export const PATH_FRONT_LOGIN = PATH_FRONT + PATH_REL_LOGIN;
export const PATH_FRONT_PROFILE = PATH_FRONT + PATH_REL_PROFILE;

// PANEL
export const PATH_PANEL_PROFILE = PATH_PANEL + PATH_REL_PROFILE;

// export const PATH_PANEL_ACCOUNTS = PATH_PANEL + PATH_REL_ACCOUNTS;
// export const PATH_PANEL_OPTIONS = PATH_PANEL + PATH_REL_OPTIONS;


// PANEL ADMIN

export const PATH_PANEL_ADMIN_ACCOUNTS = PATH_PANEL_ADMIN + PATH_REL_ACCOUNTS;
export const PATH_PANEL_ADMIN_OPTIONS = PATH_PANEL_ADMIN + PATH_REL_OPTIONS;
export const PATH_PANEL_ADMIN_PERMISSIONS = PATH_PANEL_ADMIN + PATH_REL_PERMISSIONS;
export const PATH_PANEL_ADMIN_ROLES = PATH_PANEL_ADMIN + PATH_REL_ROLES;
export const PATH_PANEL_ADMIN_POSTS = PATH_PANEL_ADMIN + PATH_REL_POSTS;
export const PATH_PANEL_ADMIN_MEDIA = PATH_PANEL_ADMIN + PATH_REL_MEDIA;

export const PATH_PANEL_ADMIN_NOTIFICATIONS = PATH_PANEL_ADMIN + PATH_REL_NOTIFICATIONS;

export const PATH_PANEL_ADMIN_NOTIFICATIONS_EXEC_STATES = PATH_PANEL_ADMIN_NOTIFICATIONS + PATH_REL_PARTS + PATH_REL_EXEC_STATES;
export const PATH_PANEL_ADMIN_NOTIFICATIONS_TYPES = PATH_PANEL_ADMIN_NOTIFICATIONS + PATH_REL_PARTS + PATH_REL_NOTIFICATION_TYPES;
export const PATH_PANEL_ADMIN_NOTIFICATIONS_EXECUTORS = PATH_PANEL_ADMIN_NOTIFICATIONS + PATH_REL_PARTS + PATH_REL_EXECUTORS;
export const PATH_PANEL_ADMIN_NOTIFICATIONS_ASSIGNS = PATH_PANEL_ADMIN_NOTIFICATIONS + PATH_REL_PARTS + PATH_REL_ASSIGNS;

